apiVersion: apps/v1
kind: Deployment
metadata:
  name: verkoupe
  annotations:
    owner: "joaovitor819oqueres@gmail.com"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: verkoupe
  template:
    metadata:
      labels:
        app: verkoupe
    spec:
      containers:
        - name: verkoupe-core
          image: verkoupedaemon:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: daemon
spec:
  selector:
    app: verkoupe
  ports:
    - port: 8080
      targetPort: 8080