apiVersion: apps/v1
kind: Deployment
metadata:
  name: view
  annotations:
    owner: "joaovitor819oqueres@gmail.com"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: view
  template:
    metadata:
      labels:
        app: view
    spec:
      containers:
        - name: verkoupe-view
          image: verkoupeview:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: view-secret
---
apiVersion: v1
kind: Service
metadata:
  name: view
spec:
  selector:
    app: view
  ports:
    - port: 80
      targetPort: 80
